---

## 💖 حمایت مالی / Support the Project

اگر این پروژه برای شما مفید بوده و قصد حمایت از توسعه آن را دارید، می‌توانید از طریق آدرس‌های رمزارز (Crypto) زیر حمایت کنید:

| Network | Currency | Wallet Address |
| :--- | :--- | :--- |
| **BNB Smart Chain (BSC)** | USDC | `0x10B549E709724bDfC647F7Ea55DD0a99f8007352` |
| **Ethereum (ETH)** | USDC | `0x10B549E709724bDfC647F7Ea55DD0a99f8007352` |
| **Solana (SOL)** | USDC | `GAPGPTMASKTOKEN7x540nsnjajX0X` |

> از حمایت و همراهی شما سپاسگزارم! ❤️
